### ISSUE TITLE
NFS mount error

### ISSUE THREAD

**Issue by dieterve** [openminds/sneakers#17]
I have the following config:

```
project:
    app_directory: "/Users/dieter/Sites/project.dev/"
    type: "php54"
    http_port: 8022                                                                                                                                                                                     
    memory: 1024
    nfs: true #NFS is not supported on windows!
    php_xdebug: true
```

After `vagrant up` I get this error:

```
$ vagrant up project
Bringing machine 'project' up with 'virtualbox' provider...
[project] Importing base box 'debian-6.0.7-amd64-ruby1.9.3.box'...
[project] Matching MAC address for NAT networking...
[project] Setting the name of the VM...
[project] Clearing any previously set forwarded ports...
Pruning invalid NFS exports. Administrator privileges will be required...
Password:
[project] Creating shared folders metadata...
[project] Clearing any previously set network interfaces...
[project] Preparing network interfaces based on configuration...
[project] Forwarding ports...
[project] -- 22 => 2222 (adapter 1)
[project] -- 8022 => 8022 (adapter 1)
[project] Booting VM...
[project] Waiting for VM to boot. This can take a few minutes.
[project] VM booted and ready for use!
[project] Setting hostname...
[project] Configuring and enabling network interfaces...
[project] Mounting shared folders...
[project] -- /vagrant
[project] -- /tmp/vagrant-chef-1/chef-solo-2/roles
[project] -- /tmp/vagrant-chef-1/chef-solo-1/cookbooks
[project] Exporting NFS shared folders...
Preparing to edit /etc/exports. Administrator privileges will be required...
[project] Mounting NFS shared folders...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

mount -o vers=3 10.0.2.1:'/Users/dieter/Sites/project.dev' /home/vagrant/apps/default
```

I logged in to the vbox via `vagrant ssh project` to manually execute the command:

```
vagrant@project:~$ sudo mount -o vers=3 10.0.2.1:'/Users/dieter/Sites/project.dev' /home/vagrant/apps/default 
mount.nfs: No route to host
```

Pinging to the 10.0.2.1 IP fails on the vbox but works from my local.

The issue is also going on here but no real solution is provided: https://github.com/mitchellh/vagrant/issues/1744. I tried some of the solutions, none of them worked. I finally got it to work by readding this line from a previous commit: https://github.com/openminds/sneakers/commit/f0dfe86d3431585c424c8bd581449a2b490d076c#L1R19

So my Vagrantfile changes look like:

```
$ git diff
diff --git a/Vagrantfile b/Vagrantfile
index cffab9b..2fe3f8c 100644
--- a/Vagrantfile
+++ b/Vagrantfile
@@ -16,7 +16,7 @@ Vagrant::Config.run do |config|
       node.vm.host_name = name
       node.vm.forward_port box['http_port'], box['http_port']
       node.vm.forward_port 3306, box['mysql_port'] if box['mysql_port']
-      node.vm.network :hostonly, "#{box['ip'] || '10.0.2.42'}" if box['nfs'] || box['ip']
+      node.vm.network :hostonly, "192.168.33.10" if box['nfs']
       Vagrant.configure("2") do |config|
         config.vm.provider :virtualbox do |vb|
           vb.customize ["modifyvm", :id, "--memory", "#{box['memory']}"]
```

So I don't know if this is a Sneakers issue, a Vagrant issue or a environment issue but this seems like the logically place to report it.

Vagrant version: 1.2.2
VirtualBox version: 4.2.16 r86992
