### ISSUE TITLE
ps_files_cleanup_dir: opendir(/var/lib/php5) failed

### ISSUE THREAD

**Issue by dieterve** [openminds/sneakers#39]
At random times I get the following error:

```
ps_files_cleanup_dir: opendir(/var/lib/php5) failed: Permission denied.
```

Found some info about it:
- http://somethingemporium.com/2007/06/obscure-error-with-php5-on-debian-ubuntu-session-phpini-garbage
- http://stackoverflow.com/questions/2904862/issues-with-php-5-3-and-sessions-folder/2952173
# Config

```
project:
    app_directory: "/Users/dieter/Sites/project.dev/"
    type: "php54"
    http_port: 8024
    memory: 1024
    nfs: true #NFS is not supported on windows!
    php_xdebug: true
```
# Versions
- Vagrant 1.3.1
- Virtualbox 4.2.18 r88780
