### ISSUE TITLE
Nginx errors

### ISSUE THREAD

**Issue by WouterSioen** [openminds/sneakers#44]
I get this error in my nginx error log:
2013/11/28 11:58:14 [error] 8792#0: *7 upstream sent too big header while reading response header from upstream, client: 10.0.2.2, server: localhost, request: "GET /app_dev.php HTTP/1.1", upstream: "http://127.0.0.1:42/app_dev.php", host: "127.0.0.1:8011"

This is my sneakers config (on a Mac, Vagrant 1.3.5, VirtualBox 4.2.16):

```
mysite:
  app_directory: "/Users/woutersioen/Sites/mysite/"
  documentroot_suffix: "web"
  type: "php54"
  http_port: 8011
  memory: 1024
  php_xdebug: 1
```

I don't have a lot of headers When i execute this command in the terminal:

```
curl -s -D - 'http://127.0.0.1.dev:8011/app_dev.php' -o /dev/null
```

It returns this:

```
HTTP/1.1 200 OK
Server: nginx/1.4.2
Date: Thu, 28 Nov 2013 11:02:58 GMT
Content-Type: text/html; charset=UTF-8
Transfer-Encoding: chunked
Connection: keep-alive
X-Powered-By: PHP/5.4.21-1~dotdeb.0
Cache-Control: no-cache
X-Debug-Token: 7c6d26
Vary: Accept-Encoding
X-Proxy: levis
```

It doesn't look tike there are way too many headers. I tried raising the proxy and the fastcgi buffers in the nginx config as google suggested but this didn't solve my problem.
